### ISSUE TITLE
improper handling of ima signature and hashes

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#1030] opened 2022-06-14 10:04 UTC
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: CentOS Stream 9
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: current upstream 1268609...

# Description 
From https://github.com/RedHat-SP-Security/keylime-tests/pull/123 I am running the following test sequence
```
           /setup/configure_tpm_emulator
            /setup/install_upstream_keylime
            /setup/configure_kernel_ima_module/ima_policy_signing
            /functional/basic-attestation-on-localhost
```
in particular the setup is made using the `tmt` tool
```
tmt -c distro=centos-stream-9 run -vvv plan -n upstream prepare discover -h fmf -t /setup/configure_tpm_emulator -t /setup/install_upstream_keylime -t /setup/configure_kernel_ima_module/ima_policy_signing -t /functional/basic-attestation-on-localhost  provision -h virtual -i CentOS-Stream-9 -c system execute login finish
```
These tests pass. Please note that despite configuring a system with ima_sig template the test attestation scenario does not work with signatures on tis own as it doesn't pass a signature when adding an agent.

Now I install `bash` RPM along with its signatures.
```
yum -y install rpm-plugin-ima
yum -y reinstall bash
```
and I execute `/functional/basic-attestation-on-localhost` manually once more.
```
cd /var/tmp/tmt/run-*/plans/upstream-keylime-tests-github-ci/discover/default/tests/functional/basic-attestation-on-localhost/
./test/sh
```
This time the test fails. Also note that while files from `bash` RPM do have evm signatures installed these files are on the excludelist.
```
# cat excludelist.txt 
/afs(/.*)?
/bin(/.*)?
/boot(/.*)?
/dev(/.*)?
/etc(/.*)?
/home(/.*)?
/lib(/.*)?
/lib64(/.*)?
/media(/.*)?
/mnt(/.*)?
/opt(/.*)?
/proc(/.*)?
/root(/.*)?
/run(/.*)?
/sbin(/.*)?
/srv(/.*)?
/sys(/.*)?
/tmp(/.*)?
/usr(/.*)?
/var(/.*)?
/sysroot/etc/fstab
/dracut-state.sh
/keylime-tests/basic-attestation-on-localhost-UvK3j(/.*)?
```
The error I see is after adding an agent, its status is Invalid Quote.
```
2022-06-14 05:42:53.364 - keylime.tenant - INFO - Agent Info:
{"d432fbb3-d2f1-4a97-9ef7-75bd81c00000": {"operational_state": "Invalid Quote", "v": "08hACNmWhrOiMZkzNVLUXkIt9XCfIM8HJ9Y4DA1Pkn8=", "ip": "127.0.0.1", "port": 9002, "tpm_policy": "{\"22\": [\"0000000000000000000000000000000000000001\", \"0000000000000000000000000000000000000000000000000000000000000001\", \"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001\", \"ffffffffffffffffffffffffffffffffffffffff\", \"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\", \"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\"], \"15\": [\"0000000000000000000000000000000000000000\", \"0000000000000000000000000000000000000000000000000000000000000000\", \"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\"], \"mask\": \"0x408400\"}", "meta_data": "{\"cert_serial\": 2, \"subject\": \"OU=53,O=MITLL,L=Lexington,ST=MA,CN=d432fbb3-d2f1-4a97-9ef7-75bd81c00000,C=US\"}", "allowlist_len": 6, "mb_refstate_len": 0, "accept_tpm_hash_algs": ["sha512", "sha384", "sha256", "sha1"], "accept_tpm_encryption_algs": ["ecc", "rsa"], "accept_tpm_signing_algs": ["ecschnorr", "rsassa"], "hash_alg": "sha256", "enc_alg": "rsa", "sign_alg": "rsassa", "verifier_id": "default", "verifier_ip": "127.0.0.1", "verifier_port": 8881, "severity_level": 6, "last_event_id": "ima.validation.ima_hash"}}
```

Multiple revocation notifications are being sent, adding first two below
```
{"msg": "{\"type\": \"revocation\", \"ip\": \"127.0.0.1\", \"agent_id\": \"d432fbb3-d2f1-4a97-9ef7-75bd81c00000\", \"port\": 9002, \"tpm_policy\": \"{\\\"22\\\": [\\\"0000000000000000000000000000000000000001\\\", \\\"0000000000000000000000000000000000000000000000000000000000000001\\\", \\\"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001\\\", \\\"ffffffffffffffffffffffffffffffffffffffff\\\", \\\"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\\\", \\\"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\\\"], \\\"15\\\": [\\\"0000000000000000000000000000000000000000\\\", \\\"0000000000000000000000000000000000000000000000000000000000000000\\\", \\\"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\\\"], \\\"mask\\\": \\\"0x408400\\\"}\", \"meta_data\": \"{\\\"cert_serial\\\": 2, \\\"subject\\\": \\\"OU=53,O=MITLL,L=Lexington,ST=MA,CN=d432fbb3-d2f1-4a97-9ef7-75bd81c00000,C=US\\\"}\", \"event_time\": \"Tue Jun 14 05:41:49 2022\", \"event_id\": \"ima.validation.ima_hash\", \"severity_label\": \"emergency\", \"context\": \"{\\\"message\\\": \\\"IMA template hash does not match the calculated hash.\\\", \\\"expected\\\": \\\"b'\\\\\\\\xffo\\\\\\\\xe6\\\\\\\\xbaL\\\\\\\\xa4\\\\\\\\x10{>\\\\\\\\xd1t\\\\\\\\xe0}\\\\\\\\x80\\\\\\\\xf7\\\\\\\\xba\\\\\\\\xf8\\\\\\\\xd5w\\\\\\\\xee'\\\", \\\"got\\\": \\\"b'(\\\\\\\\x00\\\\\\\\x00\\\\\\\\x00sha256:\\\\\\\\x004,i2E\\\\\\\\x0b\\\\\\\\xbb\\\\\\\\x1aG\\\\\\\\x86O0\\\\\\\\xbe~S\\\\\\\\xc2-ha\\\\\\\\x83\\\\\\\\x8d>\\\\\\\\xfc\\\\\\\\x8a\\\\\\\\xbb\\\\\\\\xbb\\\\\\\\xbaG\\\\\\\\xdc\\\\\\\\xa5\\\\\\\\x80j\\\\\\\\xef\\\\\\\\x00\\\\\\\\x00\\\\\\\\x00/usr/bin/bash 0302047c435bb5670030650230425145d71be6888dad039c721970e56cf55968acb3ce1ef9d9fb523c622911b89a4814f464d6b9f02a7c29f4b4e7bf4d023100fc3e6433d05aab8690625c9cab99341fbdebb7ff42869b630ff71b695b6b8078f82499408f52ae94ecc42624f3ad1cbe\\\\\\\\x00\\\\\\\\x00\\\\\\\\x00\\\\\\\\x00\\\\\\\\x00'\\\"}\"}", "signature": "w+w1F9xrDEuEQ+rM+j5VewQEfAXZScfBDX+95XMH5lViKDZJl0/Ql6aHhRwO/iW1EARU51rxD3jOrE0lxTwwTGgYhD8++AWegA0Gn4j6dDWfpgtogfcnlXQoxBtkk5S+JaAL+QrgiQle+6ahXzMs5g+6cgKxqFhXt+AtCeLeVeaXxXyQ0ur79fGPhwSsxjJeEYs8aLrWxJz+pv0YA5HrUnuOuBd/6tO1G63lGTVdln8Zo6jZW135tFJtiftbaom/j2nCwnRl/ZHOzf6NSy1i3bC7JWYdOxxsTyazm9T2c3dEUOO02vDmVwKWbfaHoVvnyhqYO3IoYxN6gwvu9E4xFw=="}POST / HTTP/1.1

{"msg": "{\"type\": \"revocation\", \"ip\": \"127.0.0.1\", \"agent_id\": \"d432fbb3-d2f1-4a97-9ef7-75bd81c00000\", \"port\": 9002, \"tpm_policy\": \"{\\\"22\\\": [\\\"0000000000000000000000000000000000000001\\\", \\\"0000000000000000000000000000000000000000000000000000000000000001\\\", \\\"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001\\\", \\\"ffffffffffffffffffffffffffffffffffffffff\\\", \\\"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\\\", \\\"ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\\\"], \\\"15\\\": [\\\"0000000000000000000000000000000000000000\\\", \\\"0000000000000000000000000000000000000000000000000000000000000000\\\", \\\"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\\\"], \\\"mask\\\": \\\"0x408400\\\"}\", \"meta_data\": \"{\\\"cert_serial\\\": 2, \\\"subject\\\": \\\"OU=53,O=MITLL,L=Lexington,ST=MA,CN=d432fbb3-d2f1-4a97-9ef7-75bd81c00000,C=US\\\"}\", \"event_time\": \"Tue Jun 14 05:41:49 2022\", \"event_id\": \"ima.validation.ima_hash\", \"severity_label\": \"emergency\", \"context\": \"{\\\"message\\\": \\\"IMA template hash does not match the calculated hash.\\\", \\\"expected\\\": \\\"b'\\\\\\\\xffo\\\\\\\\xe6\\\\\\\\xbaL\\\\\\\\xa4\\\\\\\\x10{>\\\\\\\\xd1t\\\\\\\\xe0}\\\\\\\\x80\\\\\\\\xf7\\\\\\\\xba\\\\\\\\xf8\\\\\\\\xd5w\\\\\\\\xee'\\\", \\\"got\\\": \\\"b'(\\\\\\\\x00\\\\\\\\x00\\\\\\\\x00sha256:\\\\\\\\x004,i2E\\\\\\\\x0b\\\\\\\\xbb\\\\\\\\x1aG\\\\\\\\x86O0\\\\\\\\xbe~S\\\\\\\\xc2-ha\\\\\\\\x83\\\\\\\\x8d>\\\\\\\\xfc\\\\\\\\x8a\\\\\\\\xbb\\\\\\\\xbb\\\\\\\\xbaG\\\\\\\\xdc\\\\\\\\xa5\\\\\\\\x80j\\\\\\\\xef\\\\\\\\x00\\\\\\\\x00\\\\\\\\x00/usr/bin/bash 0302047c435bb5670030650230425145d71be6888dad039c721970e56cf55968acb3ce1ef9d9fb523c622911b89a4814f464d6b9f02a7c29f4b4e7bf4d023100fc3e6433d05aab8690625c9cab99341fbdebb7ff42869b630ff71b695b6b8078f82499408f52ae94ecc42624f3ad1cbe\\\\\\\\x00\\\\\\\\x00\\\\\\\\x00\\\\\\\\x00\\\\\\\\x00'\\\"}\"}", "signature": "w+w1F9xrDEuEQ+rM+j5VewQEfAXZScfBDX+95XMH5lViKDZJl0/Ql6aHhRwO/iW1EARU51rxD3jOrE0lxTwwTGgYhD8++AWegA0Gn4j6dDWfpgtogfcnlXQoxBtkk5S+JaAL+QrgiQle+6ahXzMs5g+6cgKxqFhXt+AtCeLeVeaXxXyQ0ur79fGPhwSsxjJeEYs8aLrWxJz+pv0YA5HrUnuOuBd/6tO1G63lGTVdln8Zo6jZW135tFJtiftbaom/j2nCwnRl/ZHOzf6NSy1i3bC7JWYdOxxsTyazm9T2c3dEUOO02vDmVwKWbfaHoVvnyhqYO3IoYxN6gwvu9E4xFw=="}
```

## Expected behavior vs. actual behavior 
The agent should pass attestation because even though a signature from `/usr/bin/bash` cannot be verified it matches the exclude list.

## Steps to reproduce problem
1. described above

# Relevant logs
verifier log
```
Jun 14 05:41:49 testcloud keylime_verifier[7837]: 2022-06-14 05:41:49.315 - keylime.tpm - INFO - TPM2-TOOLS Version: 5.0
Jun 14 05:41:49 testcloud keylime_verifier[7837]: 2022-06-14 05:41:49.325 - keylime.tpm - INFO - Checking IMA measurement list on agent: d432fbb3-d2f1-4a97-9ef7-75bd81c00000
Jun 14 05:41:49 testcloud keylime_verifier[7837]: 2022-06-14 05:41:49.339 - keylime.ima - ERROR - IMA ERRORS: Some entries couldn't be validated. Number of failures in modes: ImaSig 1.
Jun 14 05:41:49 testcloud keylime_verifier[7837]: 2022-06-14 05:41:49.380 - keylime.revocation_notifier - INFO - Sending revocation event via webhook...
Jun 14 05:41:49 testcloud keylime_verifier[7837]: 2022-06-14 05:41:49.391 - keylime.cloudverifier - WARNING - Agent d432fbb3-d2f1-4a97-9ef7-75bd81c00000 failed, stopping polling
```

ascii_runtime_measurements file can be downloaded using
```
curl -O https://transfer.sh/SS8Eay/ascii_runtime_measurements.txt
```

**Comment by THS-on** [comment] 2022-06-14 11:55
I found now root cause of this issue.

Signatures are distributed in CentOS 9 Stream the following way:
1. Signatures are added to the RPM header (e.g. with rpmsign)
2. rpm-plugin-ima takes those signatures, converts them to the IMA format
3. signatures are attached to the file using the `security.ima` extended file attribute

Keylime does the following with a signature:
1. Parses the header
2. validates that the length is correct
3. validates the signature against the provided keyring

If the parsing of the signature fails we currently assume that we had whitespace in the path and and just add it to the filename.

The issue is that the RPM plugin did not specify the actual size of the signature, instead they just put in the maximal length. This caused our parser to fail. Now our path is now wrong because the it includes also the signature and therefore the template_hash sanity check fails.

More details and the fix is already in the RPM repo and can be found here: https://github.com/rpm-software-management/rpm/commit/07f1d3132f0c7b7ecb69a47a9930edb534a9250e

**Comment by dmnks** [comment] 2022-06-14 13:54
> Edit: It seems to not be this bug exactly, but it is something related to the rpm plugin.

Actually it doesn't seem to be related to the IMA plugin; it just calls into RPM to get the signatures in binary format and stores them into the extended file attributes.

**Comment by THS-on** [comment] 2022-06-14 14:02
@dmnks thanks for taking a look at this issue.

> Actually it doesn't seem to be related to the IMA plugin; it just calls into RPM to get the signatures in binary format and stores them into the extended file attributes.

Ok. Do you have an idea why the following signature then has the wrong length (26368 instead of 103) in the header?

```
0302047c435bb5670030650230425145d71be6888dad039c721970e56cf55968acb3ce1ef9d9fb523c622911b89a4814f464d6b9f02a7c29f4b4e7bf4d023100fc3e6433d05aab8690625c9cab99341fbdebb7ff42869b630ff71b695b6b8078f82499408f52ae94ecc42624f3ad1cbe
```

This is the signature for bash in from IMA log provided above.

> Why don't you just get the length from the actual hex string? We [do](https://github.com/rpm-software-management/rpm/blob/07f1d3132f0c7b7ecb69a47a9930edb534a9250e/lib/rpmfi.c#L572) [just that](https://github.com/rpm-software-management/rpm/blob/07f1d3132f0c7b7ecb69a47a9930edb534a9250e/lib/rpmfi.c#L1481) in RPM.

We do that and compare it against the length in the header as a sanity check.

https://github.com/keylime/keylime/blob/9a60e8218d21b7d178be9fb90bbd476ba2aa83ba/keylime/ima/ast.py#L101-L108

**Comment by dmnks** [comment] 2022-06-14 14:39
> @dmnks thanks for taking a look at this issue.

Glad to help!

> Ok. Do you have an idea why the following signature then has the wrong length (26368 instead of 103) in the header?

What do you mean by "has" here? Where is this length stored? Remember we don't store individual file signature lengths in the header.

> We do that and compare it against the length in the header as a sanity check.
> 
> https://github.com/keylime/keylime/blob/9a60e8218d21b7d178be9fb90bbd476ba2aa83ba/keylime/ima/ast.py#L101-L108

I'm not familiar with the code base here, but where do you get the header data from exactly?

**Comment by dmnks** [comment] 2022-06-14 14:51
Looking closer at the surrounding code linked above, this really doesn't seem to have anything to do with *RPM headers*. I wonder if this term is used within the context of IMA? If so, that could be where the confusion comes from.

**Comment by THS-on** [comment] 2022-06-14 14:54
> What do you mean by "has" here? Where is this length stored? Remember we don't store individual file signature lengths in the header.

I mean the IMA signature. IMA signatures have the following format
```
struct signature_v2_hdr {
	uint8_t type;		/* xattr type */
	uint8_t version;	/* signature format version */
	uint8_t	hash_algo;	/* Digest algorithm [enum hash_algo] */
	__be32 keyid;		/* IMA key identifier - not X509/PGP specific */
	__be16 sig_size;	/* signature size */
	uint8_t sig[];		/* signature payload */
};
```
See: https://elixir.bootlin.com/linux/latest/source/security/integrity/integrity.h#L126

The first five struct members are what I mean with "header". This header includes the signature length. We extract that length and compare it against the bytes that we got from the IMA log. In the provided example we expect 103, but `sig_size` contains 26368.

**Comment by THS-on** [comment] 2022-06-14 14:55
> Looking closer at the surrounding code linked above, this really doesn't seem to have anything to do with RPM headers. I wonder if this term is used within the context of IMA? If so, that could be where the confusion comes from.

Yes I meant the IMA signature header, not the RPM one. Sorry for the confusion.

**Comment by dmnks** [comment] 2022-06-14 15:23
Oh, that explains it, thanks! I wasn't aware of the internal structure of these signatures, but of course they'd contain some kind of a header structure!

So this indeed looks like the signature size is *computed* incorrectly at *sign* time before it's stored in the corresponding RPM tag `RPMTAG_FILESIGNATURES`. That leads to the [signFile()](https://github.com/rpm-software-management/rpm/blob/fdcd486b43652bb32dd40ef84f40b11dc6d9dda5/sign/rpmsignfiles.c#L37) function in RPM where call into `sign_hash()` defined in `imaevm.h`, however it's really impossible to say (without running this through a debugger) whether the bug lies within our code or libimaemv's, I'm afraid.

**Comment by dmnks** [comment] 2022-06-14 15:26
If it was a bug in RPM's signing routine, it would have to be some undefined use of the `sign_hash()` API function, e.g. by passing it wrong parameters. I'd risk to say that this is more likely to be an issue within libimaevm.

**Comment by dmnks** [comment] 2022-06-14 15:27
Do you see this with other packages than just `bash`?

**Comment by dmnks** [comment] 2022-06-14 15:31
> Ok. Do you have an idea why the following signature then has the wrong length (26368 instead of 103) in the header?

This size mismatch is also quite suspicious, it almost seems like there's some uninitialized variable in use.

**Comment by dmnks** [comment] 2022-06-14 16:07
I just tried to reproduce this on a c9s system with [ima-inspect](https://download.opensuse.org/repositories/security/openSUSE_Factory/src/ima-inspect-0.14-13.30.src.rpm) on the `/usr/bin/bash` file from `bash-5.1.8-4.el9.x86_64` but the signatures seemed totally fine:

```
$ ima_inspect /usr/bin/bash
/usr/bin/bash

security.ima
------------
digital signature version 2
digest algorithm: sha256
key-id v2 (gpg compatible): 7c435bb5
signature length: 824 bits
signature data:

3065023100fd10f9 a5f8e6a700c1e119 a7cd4279a11eaa8e 37a9712ff491f3aa 74e60da9fbf8fe6b 02ecaae0bca257a9 8d078e8c63023064 3acb687d6a59e9bd
9a1196278dae017a a7e88338e4eccda1 26a2321df86c0424 9e26953093f1f871 6dae570c6e8a22

security.evm
------------
no such attribute
```

**Comment by dmnks** [comment] 2022-06-14 16:11
OK, I *can* reproduce something with [bash-5.1.8-2.el9.x86_64](http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/bash-5.1.8-2.el9.x86_64.rpm):

```
$ ima_inspect /usr/bin/bash
/usr/bin/bash

security.ima
------------
digital signature version 2
RuntimeError: premature end of attribute data (sig)


security.evm
------------
no such attribute

**Comment by kkaarreell** [comment] 2022-06-14 17:11
I can confirm that. For some reason CI systems use older image with bash-5.1.8-2.el9. After updating to -4 things seems to work well. So hopefully these wrong signatures were present only for older builds.
I am sorry for the noise. Probably we can close this issue.

**Comment by dmnks** [comment] 2022-06-14 17:12
Good to know, thanks!

**Comment by THS-on** [comment] 2022-06-14 17:54
I'll close this now. If we see this again in the future, now we know where to search.

**Closed by THS-on** 2022-06-14 17:54 UTC
