### ISSUE TITLE
A restart of agent host causes agent status to fail

### ISSUE THREAD

**Issue by kaifeng** [keylime/keylime#481] opened 2020-12-24 12:08 UTC
When the host system of an agent restarts, agent status is set to fail due to verifier unable to get status from the agent.
There is retrying but the default time interval and retry count are quite small (1 sec, 10 times), a system restart can't complete in such a short time. Though we could raise the configuration value here, but the point is, an invalid quote can lead to fail state, while unreachable for a period of time doesn't mean the host is untrusted, there is no way to tell their difference. Furthermore, when an untrusted host restarts, it is very possible to be restored to the trusted state, and we have no mechanism to restore periodic checking automatically.

The thing I come up at this moment, we could have an informational field to record why an agent is in current state when there is a state change, or add more agent states to get more finer grained agent status.

Dec 24 14:59:03 Controller-1 keylime_verifier[458583]: 2020-12-24 14:59:03.306 - keylime.cloudverifier - INFO - process_agent: Computer-TPM
Dec 24 14:59:03 Controller-1 keylime_verifier[458583]: 2020-12-24 14:59:03.320 - keylime.cloudverifier - WARNING - agent Computer-TPM was not reachable for quote in 10 tries, setting state to FAILED
Dec 24 14:59:03 Controller-1 keylime_verifier[458583]: 2020-12-24 14:59:03.320 - keylime.cloudverifier - INFO - process_agent: Computer-TPM
Dec 24 14:59:03 Controller-1 keylime_verifier[458583]: 2020-12-24 14:59:03.332 - keylime.cloudverifier - WARNING - agent Computer-TPM failed, stopping polling

**Comment by THS-on** [comment] 2022-03-14 17:02
With the failure tagging system the reason why the system failed is visible.  Restarting a failed agent works with `PUT /{UUID}/reactivate`. Failures caused by an agent restart are tracked in #656.
Validating the clock data of a quote is part of https://github.com/keylime/enhancements/issues/59.

**Comment by THS-on** [comment] 2022-06-29 06:06
I close this because we now track the reason why an agent failed and reboot detection via clock validation is part of https://github.com/keylime/enhancements/issues/59.

**Closed by THS-on** 2022-06-29 06:06 UTC
Labels: needs-triage
