### ISSUE TITLE
Multiple types of failure if keylime_agent is restarted mid-attestation.

### ISSUE THREAD

**Issue by galmasi** [keylime/keylime#656] opened 2021-04-29 00:42 UTC
# Environment
 * OS / version: Fedora/32 *and* Ubuntu 18.04 (observed on both) -- we theorize there is no dependency
 * Processor architecture: x86_64 (likely irrelevant)
 * TPM Manufacturer: Infineon _and_ swtpm (Stefan)
 * Keylime version: 6.1.0+, but we think the problem is pervasive
 
# Disclaimer

I do not claim perfect understanding of the causes for the failures under discussion. Feel free to comment and contribute test outcomes.

# Description 
We have observed two separate problems if keylime agent is restarted while attestation is ON. Apologies for the long message; I am attempting to describe two problems with different root causes and likely requite different fixes; but they are triggered by the same actions. Both are heisenbugs -- they manifest occasionally.

Problem 1: attestation fails on the node -- the verifier is unable to decode the quote sent back by the keylime agent. This can be fixed by disregarding the attestation failure and re-adding the keylime agent by means of a tenant "add" command.

Problem 2: an extra authentication session is left in the TPM device. Depending on the value of the device property TPM2_PT_CONTEXT_GAP_MAX, a failure will happen 64 to 64k quotes *later* (on real systems this usually means a day and a half of delay before the error). After that tpm2_quote fails consistently.

In this situation the only fix we know of is to issue a `tpm2_flushcontext -s` command on the machine.

## Expected behavior vs. actual behavior 

* Expected behavior: attestation *always* continues correctly even if the keylime agent was restarted.
* Actual behavior: attestation fails sporadically after keylime agent restarts in one of two different ways. 

## Steps to reproduce problem
1. Set up a keylime system with at least a verifier, registrar and an agent.
2. Turn on attestation for the agent by means of a `keylime_tenant add .... ` command.
3. Wait for the situation to stabilize while watching the keylime agent's log and the keylime verifier's log.
4. Restart the keylime agent (in production they usually issue a systemd command to do it, but @maugustosilva @apoorvemohan observed this by running the agent manually and interrupting it with ctrl+c)
5. In some cases attestation fails immediately (problem 1)
6. In some cases the system appears to perform normally after keylime agent restart, but fails minutes or hours later without any additional action taken (problem 2)

# Relevant logs

*   **Failure mode 1** (verifier cannot decrypt received quote and attestation fails immediately)
``` 
2021-04-28 14:21:52.618 - keylime.tpm - ERROR - Error verifying quote: Command: ['tpm2_checkquote', '-u', '/tmp/tmpeidwsjkr', '-m', '/tmp/tmpq4fqgg_y', '-s', '/tmp/tmp12sct4co', '-f', '/tmp/tmph6b0brbw', '-g', 'sha256', '-q', '704643455a5a476e754443506e47593657636549'] returned 1, expected 0, output [b'pcrs:\n', b'  sha256:\n', b'    16: 0x3BA7C48470EAA90D08F75CDEE9611E7E91332BF45541890E344C2C010D42ECCA\n', b'    23: 0x0000000000000000000000000000000000000000000000000000000000000000\n', b'sig: 1251df7d1e2224f907db1efc79529ba59b65d30da5df06957dbfe57bb573cf02ab232d07d614e9ddfd1c57e7b749e0732547cc91d756e0e3d8e6cfa0c8982a8208541acadfc431727343fe8ce1b242d82657c3dd016d3b7369081c244f2d5898fb272209a5d323a55005c735f75df4c3c017c5d3d9f88ceffb2a06d6a7ededb1fbb8caa70c014c201bc67d2d2a346dd3276e659658624f61cb9c5e47b07ca637d7f286e420cd6d82c538ca338ac4ec222db6c99429c51423e76cf8af71756a4b300c92ad396825403e465d858472e82b2024016e07d3ded8c923d760c79b75604ce642544d941fa87f5fa8cfa8497e1faeafc91bf301401bcf6c21abde7df344\n'], stderr [b'WARNING:marshal:src/tss2-mu/tpm2b-types.c:303:Tss2_MU_TPM2B_DIGEST_Unmarshal() buffer_size: 451 with offset: 10 are insufficient for object of size 18766 \n', b'WARNING:marshal:src/tss2-mu/tpm2b-types.c:361:Tss2_MU_TPM2B_PUBLIC_Unmarshal() buffer_size: 451 with offset: 2 are insufficient for object of size 11565 \n', b'ERROR: Error validating signed message with public key provided\n', b'ERROR: Verify signature failed!\n', b'ERROR: Unable to run tpm2_checkquote\n']
2021-04-28 14:21:52.619 - keylime.tpm - ERROR - Command: ['tpm2_checkquote', '-u', '/tmp/tmpeidwsjkr', '-m', '/tmp/tmpq4fqgg_y', '-s', '/tmp/tmp12sct4co', '-f', '/tmp/tmph6b0brbw', '-g', 'sha256', '-q', '704643455a5a476e754443506e47593657636549'] returned 1, expected 0, output 
```

* **Failure mode** 2 (keylime agent fails to run tpm2_quote after a set amount of time. Boundary condition: /dev/tmprm0 is used as the TPM device):
```
Apr 28 23:35:10 cssf-oc3-mstr0 keylime_agent[11327]: Exception: Command: ['tpm2_quote', '-c', '/var/lib/keylime/secure/tmp_8x49ard', '-l', 'sha256:0,16
', '-q', '737868716975663433446e723433736a51486166', '-m', '/tmp/tmphxb02ihl', '-s', '/tmp/tmppd995l9a', '-o', '/tmp/tmp5p_7_8i_', '-g', 'sha256', '-p'
, 'LfDonsdLI7XqwRTBXRCJ'] returned 1, expected 0, output [], stderr [b'ERROR:tcti:src/util/io.c:108:write_all() failed to write to fd 3: Bad address \n
', b'ERROR:tcti:src/tss2-tcti/tcti-device.c:126:tcti_device_transmit() wrong number of bytes written. Expected 59, wrote 0. \n', b'ERROR:esys:src/tss2-
esys/api/Esys_StartAuthSession.c:283:Esys_StartAuthSession_Async() Finish (Execute Async) ErrorCode (0x000a000a) \n', b'ERROR:esys:src/tss2-esys/api/Es
ys_StartAuthSession.c:113:Esys_StartAuthSession() Error in async function ErrorCode (0x000a000a) \n', b'ERROR: Esys_StartAuthSession(0xA000A) - tcti:IO
 failure\n', b'ERROR: Invalid key authorization\n', b'ERROR: Unable to run tpm2_quote\n']
```

* **Failure mode** 2 (same as above, but /dev/tpm0 is used as the TPM device)

```
/Esys_StartAuthSession.c:390:Esys_StartAuthSession_Finish() Received TPM Error \n', b'ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:136:Esys_StartAuthSession() Esys Finish ErrorCode (0x00000901) \n', b'ERROR: Esys_StartAuthSession(0x901) - tpm:warn(2.0): gap for context ID is too large\n' 
```

# Discussion

The first bug (attestation fails because the verifier cannot decrypt the quote) presumably fails because of a timing condition: 

* the verifier has downloaded a particular AK from the registrar
* the verifier starts a quote request on the agent by using the REST API
* the agent has meanwhile restarted, re-registered and established a new AK with the registrar
* the agent uses the new AK to encrypt the quote response
* the verifier tries to decrypt the response with the old AK, fails, and declares the agent failed.

The second bug (attestation fails eventually because of the "gap failure" on the TPM device) presumably fails because a tpm2-tools command using an AuthSession internally was interrupted mid-run and leaves a dangling AuthSession on the TPM device. I will freely admit to being somewhat in the dark about the exact sequence of events that happen here. @kgold2 or @jejb may have comments. But one noteworthy thing is that the bug can be *triggered* easily by issuing the following command on the keylime agent's node while attestation is running:
```
tpm2_startauthsession -S <bla>
```

-- and voila -- 2 minutes or a day later, attestation miraculously fails on the node.

**Comment by maugustosilva** [comment] 2021-04-29 15:18
A couple of comments:

1) It looks like "Problem 1" is actually a desired mode of operation: an `agent` "dying" or being restarted in mid-attestation should result in failures until the situation gets corrected by administrator intervention. In my mind, the actual question is: why isn't the attestation consistently and reproducibly failing in all scenarios where the `agent` restarts in mid-attestation.

2) For "Problem 2", am I being exceedingly naive by considering as a solution simply adding  `tpm2_flushcontext -s` to the list of commands issued by `tpm_init` method?

**Comment by stefanberger** [comment] 2021-04-29 19:24
> Problem 2: an extra authentication session is left in the TPM device. Depending on the value of the device property TPM2_PT_CONTEXT_GAP_MAX, a failure will happen 64 to 64k quotes _later_ (on real systems this usually means a day and a half of delay before the error). After that tpm2_quote fails consistently.
> 
> In this situation the only fix we know of is to issue a `tpm2_flushcontext -s` command on the machine.

When you start the agent you just always issue a `tpm2_flushcontext -s` and that solves it then? Just issue that command as part of the agent startup then...

But isn't this whole context swapping issue supposed to be solved by either using /dev/tpm0 via tpm2-abrmd or /dev/tpmrm0 (directly or via tpm2-abrmd?) and these left-over issues shouldn't occur unless you were talking to /dev/tpm0 directly and forgot to clean up afterwards?

**Comment by galmasi** [comment] 2021-05-03 14:54
Clearly @stefanberger talking to /dev/tpmrm0 merely postpones the problem. By maybe 9 hours, in fact -- 16,384 accesses x 2 seconds between accesses :)

Flushing the contexts seems to be the immediate fix, I believe @maugustosilva is about to raise a PR, or already has.

As for "forgot to cleanup", it looks like Issue 2 happens with some fixed percentage of probability depending on how we "catch" the keylime agent while restarting. If the keylime agent is killed while calling a tpm2-tools command (e.g. tpm2_quote) it causes an internal auth session to be abandoned.

**Comment by stefanberger** [comment] 2021-05-03 15:30
All these context/resource managers should clean up once a client disappears and leaves state behind. Since they dpon't seem to do that I guess we could try to either block signals or clean up in an exception handler, though a SIGKILL at the wrong time won't be served with either of these measures.

**Comment by jejb** [comment] 2021-05-03 15:51
On Mon, 2021-05-03 at 08:31 -0700, Stefan Berger wrote:
> All these context/resource managers should clean up once a client
> disappears and leaves state behind. Since they dpon't seem to do that

How would a resource manager know?  If a handle disappears from a RM
it's usually because a user flushed it, but it could be because the
user context saved it.  The only way to guarantee that a user can't do
this would be to block the saving of contexts, which would basically
destroy the operation of tpm2-tools.

James

**Comment by stefanberger** [comment] 2021-05-03 15:57
> How would a resource manager know? 

lost client via closed file descriptor

**Comment by jejb** [comment] 2021-05-03 16:18
On Mon, 2021-05-03 at 08:57 -0700, Stefan Berger wrote:
> > How would a resource manager know? 
> 
> lost client via closed file descriptor 

Not how does it know the client is dead, that's what it already does. 
How does it know if the client context saves a handle

James

**Comment by stefanberger** [comment] 2021-05-03 16:24
> Not how does it know the client is dead, that's what it already does. How does it know if the client context saves a handle

It would have to track all of these things that require cleaning when the client (abruptly) disappears.

**Comment by kgold2** [comment] 2021-05-03 19:36
>     1. It looks like "Problem 1" is actually a desired mode of operation: an `agent` "dying" or being restarted in mid-attestation should result in failures until the situation gets corrected by administrator intervention. In my mind, the actual question is: why isn't the attestation consistently and reproducibly failing in all scenarios where the `agent` restarts in mid-attestation.

I don't understand why this is desirable.  An agent can die for many reasons -  a reboot, a bug, a malicious program.  When it restarts, keylime should keep going.  What would an administrator do manually to correct it that SW could not do?

**Comment by maugustosilva** [comment] 2021-05-03 21:22
> > ```
> > 1. It looks like "Problem 1" is actually a desired mode of operation: an `agent` "dying" or being restarted in mid-attestation should result in failures until the situation gets corrected by administrator intervention. In my mind, the actual question is: why isn't the attestation consistently and reproducibly failing in all scenarios where the `agent` restarts in mid-attestation.
> > ```
> 
> 
> I don't understand why this is desirable.  An agent can die for many reasons -  a reboot, a bug, a malicious program.  When it restarts, keylime should keep going.  What would an administrator do manually to correct it that SW could not do?

Fair point. Allow me to be more precise then. An external component (e.g., in our production setup, the "deployer") needs to take some initiative to solve the problem of an `agent` which was just restarted and failed attestation. Not necessarily "manually" in the strict sense of "a being of the species Homo sapiens has to type commands on a keyboard", but much closer to "a component outside of the `verifier` <-> `agent` established pair needs to explicitly take some action" (e.g., delete the `agent` from `verifier` and then re-add it)

**Comment by stefanberger** [comment] 2021-05-06 17:05
> > Not how does it know the client is dead, that's what it already does. How does it know if the client context saves a handle
> 
> It would have to track all of these things that require cleaning when the client (abruptly) disappears. -> Track TPM2_ContextSave

The kernel resource manager could probably track the contexts that applications are saving but it cannot flush them with the way command line tools are used. A higher level session spanning the usage of several command line tools would have to exist that, once the session gets terminated, would need to clean up any left-over resources used during that session. The challenge would be to define what such a session would be and then how a TSS stack could detect that that session has become stale. I don't think it wouild be straight forward. The only way one could do that in the kernel resource manager would be by enforcing that  executables must be written that do all the necessary steps, that are today done across multiple command line tools, and then the kernel resource manger could do the final cleanup.

With the Intel stack we could try to give the session file a unique name or suffix so that it is recognizeable and if that session is left over from the previous run we could clear it.

```
            sesspathfd, sesspath = tempfile.mkstemp(dir=secdir)
```

It has a random name today, so makes it hard to recognize.

If the agent is not restarted  (after leaving a stale session) then another application may be running into the context gap issue. So this is likely only work-around to what seems a TPM 2 flaw.

**Comment by kgold2** [comment] 2021-05-24 20:41
>     1. It looks like "Problem 1" is actually a desired mode of operation: an `agent` "dying" or being restarted in mid-attestation should result in failures until the situation gets corrected by administrator intervention. In my mind, the actual question is: why isn't the attestation consistently and reproducibly failing in all scenarios where the `agent` restarts in mid-attestation.

I don't understand why this is desirable.  An agent can die for many reasons -  a reboot, a bug, a malicious program.  When it restarts, keylime should keep going.  What would an administrator do manually to correct it that SW could not do?

**Comment by kgold2** [comment] 2021-05-24 20:47
Perhaps the cleanest, easiest to be correct, solution is for the agent to close the connection after each attestation.  The resource manager will do any necessary flushing.

The agent 'should' flush any resources, just as a program should free malloced memory, but the close() is guaranteed to work.

The quote could be just open, load, quote, flush, close.

**Comment by kgold2** [comment] 2021-06-07 22:33
On 5/3/2021 11:51 AM, James Bottomley wrote:
> On Mon, 2021-05-03 at 08:31 -0700, Stefan Berger wrote: > All these context/resource managers should clean up once a client > disappears and leaves state behind. Since they dpon't seem to do that How would a resource manager know? 
> 
> On Mon, 2021-05-03 at 08:31 -0700, Stefan Berger wrote:
>  > All these context/resource managers should clean up once a client
>  > disappears and leaves state behind. Since they dpon't seem to do that
> 
> How would a resource manager know? If a handle disappears from a RM
> it's usually because a user flushed it, but it could be because the
> user context saved it. The only way to guarantee that a user can't do
> this would be to block the saving of contexts, which would basically
> destroy the operation of tpm2-tools.

Wouldn't a resource manager typically detect that the connection
closed because the process exited or a close() and clean up?
Where clean up means flushing the TPM and deleting objects
from RM tables?

**Comment by mpeters** [comment] 2022-03-02 14:54
Is this still a problem? I remember @maugustosilva doing some work for the agent to clean things up when it restarts.

**Comment by THS-on** [comment] 2022-03-06 10:47
We should now flush the old keys, but we still generate a new AK on startup which will cause the agent to fail attestation.

We discussed some time ago that features like a persistent AK go only into the rust-agent and we keep the TPM interaction code for the Python agent basically in maintenance mode.

**Comment by THS-on** [comment] 2022-06-14 20:15
With https://github.com/keylime/rust-keylime/pull/391 the rust agent should now work after a restart.

@galmasi can we close this? The Python agent will probably never receive that feature.

**Closed** 2022-06-29 06:02 UTC
