### ISSUE TITLE
keylime_webapp don't work after package install

### ISSUE THREAD

**Issue by dnoliver** [keylime/keylime#519] opened 2021-01-22 20:46 UTC
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora Server 33
 * Processor architecture:  x86_64
 * TPM Manufacturer:  Simulator 
 * Keylime version: 5.7.2

# Description 

`keylime_webapp` fails to start after installation.
Complains about static content missing.

## Expected behavior vs. actual behavior 

Expected: should start
Actual: fails to start

## Steps to reproduce problem
1.  `dnf install -y keylime`
2.  `keylime_webapp`

# Relevant logs

Attach any relevant log files that can help to debug your issue. 

```
[root@fedora-server keylime]# keylime_webapp
Using config file /etc/keylime.conf
2021-01-22 17:41:31.998 - keylime.tenant - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2021-01-22 17:41:31.998 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-01-22 17:41:32.007 - keylime.tenant_webapp - INFO - Starting Tenant WebApp (tornado) on port 443 use <Ctrl-C> to stop
Traceback (most recent call last):
  File "/usr/bin/keylime_webapp", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/keylime/cmd/webapp.py", line 15, in main
    tenant_webapp.main()
  File "/usr/lib/python3.9/site-packages/keylime/tenant_webapp.py", line 639, in main
    raise Exception(
Exception: Static resource directory could not be found in /usr/lib/python3.9/site-packages/keylime!

[root@fedora-server keylime]# ls /usr/lib/python3.9/site-packages/keylime
ca_impl_cfssl.py           cmd            db                      keylime_logging.py   revocation_actions      tenant_webapp.py
ca_impl_openssl.py         cmd_exec.py    httpclient_requests.py  openstack.py         revocation_notifier.py  tornado_requests.py
ca_util.py                 common.py      ima.py                  __pycache__          secure_mount.py         tpm
cloud_verifier_common.py   cryptodome.py  __init__.py             registrar_client.py  serve_uuid.py           tpm_ek_ca.py
cloud_verifier_tornado.py  crypto.py      keylime_agent.py        registrar_common.py  tenant.py               vtpm_manager.py
```

**Comment by kaifeng** [comment] 2021-01-23 06:54
Hi, this is a packaging issue I had run into, since the rpm spec is not maintained in this repo, I am afraid it has to be address by the packaging team of distributions.
For workaround, you can copy all the files under static/ from this repository to the designated location.

**Comment by lukehinds** [comment] 2021-01-23 11:47
I will take this on a ship a new release on Fedora.

**Comment by lukehinds** [comment] 2021-01-23 14:42
https://bodhi.fedoraproject.org/updates/FEDORA-2021-2c3a0c5c63

**Comment by dnoliver** [comment] 2021-01-25 16:47
After the update, the verifier and registrar cannot start.

```shell
[root@fedora-server keylime]# rpm -qa keylime
keylime-5.8.0-1.fc33.noarch

[root@fedora-server keylime]# keylime_verifier
Using config file /etc/keylime.conf
Traceback (most recent call last):
  File "/usr/bin/keylime_verifier", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_verifier')())
  File "/usr/bin/keylime_verifier", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/keylime/cmd/verifier.py", line 10, in <module>
    from keylime import cloud_verifier_tornado
  File "/usr/lib/python3.9/site-packages/keylime/cloud_verifier_tornado.py", line 22, in <module>
    from keylime import cloud_verifier_common
  File "/usr/lib/python3.9/site-packages/keylime/cloud_verifier_common.py", line 24, in <module>
    from keylime import ima_file_signatures
  File "/usr/lib/python3.9/site-packages/keylime/ima_file_signatures.py", line 25, in <module>
    import asn1
ModuleNotFoundError: No module named 'asn1'
```

**Comment by lukehinds** [comment] 2021-01-25 16:50
sorry about this @dnoliver , I should have this fixed shortly.

if it's not to much trouble could you try running `dnf install python3-pyasn1 -y` and then try again?

**Comment by dnoliver** [comment] 2021-01-25 16:55
apparently, I have python3-pyasn1 already installed:

```shell
[root@fedora-server keylime]# dnf install python3-pyasn1 -y
Last metadata expiration check: 0:53:00 ago on Mon 25 Jan 2021 12:58:38 PM -03.
Package python3-pyasn1-0.4.8-3.fc33.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by kaifeng** [comment] 2021-01-25 16:59
I also hit this today at CentOS8, python3-pyasn1 was installed already, but this is not the package keylime imports.
@stefanberger may have idea on this.

**Comment by lukehinds** [comment] 2021-01-25 17:02
I suspect its a versioning thing (finding out now), we may need to make the ima file sigs optional (if that's possible)

**Comment by lukehinds** [comment] 2021-01-25 17:04
@dnoliver so we don't disrupt you too much, if you want a temp work around just run.

pip3 install asn1

**Comment by lukehinds** [comment] 2021-01-25 17:06
ok, got it

https://pypi.org/project/asn1/ and https://pypi.org/project/pyasn1/ are different packages.

**Comment by dnoliver** [comment] 2021-01-25 17:25
`pip3 install asn1` fix the issue. But keylime_registrar run into a db update problem. Sharing the stacktrace before I clean up my environment:

```shell
[root@fedora-server keylime]# keylime_registrar
Using config file /etc/keylime.conf
2021-01-25 14:22:28.901 - keylime.keylime_db - WARNING - database_url is not set, using deprecated database configuration options
2021-01-25 14:22:28.992 - keylime.keylime_db - WARNING - database_url is not set, using deprecated database configuration options
2021-01-25 14:22:28.994 - alembic.env - INFO - Migrating database registrar
2021-01-25 14:22:28.994 - alembic.runtime.migration - INFO - Context impl SQLiteImpl.
2021-01-25 14:22:28.994 - alembic.runtime.migration - INFO - Will assume non-transactional DDL.
2021-01-25 14:22:29.009 - alembic.runtime.migration - INFO - Running upgrade  -> 8a44a4364f5a, Initial database migration
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table registrarmain already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/keylime_registrar", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_registrar')())
  File "/usr/lib/python3.9/site-packages/keylime/cmd/registrar.py", line 19, in main
    keylime.cmd.migrations_apply.apply('registrar')
  File "/usr/lib/python3.9/site-packages/keylime/cmd/migrations_apply.py", line 31, in apply
    alembic.config.main(argv=alembic_args)
  File "/usr/lib/python3.9/site-packages/alembic/config.py", line 577, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python3.9/site-packages/alembic/config.py", line 571, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python3.9/site-packages/alembic/config.py", line 548, in run_cmd
    fn(
  File "/usr/lib/python3.9/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/lib/python3.9/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python3.9/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/keylime/migrations/env.py", line 147, in <module>
    run_migrations_online()
  File "/usr/lib/python3.9/site-packages/keylime/migrations/env.py", line 127, in run_migrations_online
    context.run_migrations(engine_name=name)
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python3.9/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python3.9/site-packages/alembic/runtime/migration.py", line 520, in run_migrations
    step.migration_fn(**kw)
  File "/usr/lib/python3.9/site-packages/keylime/migrations/versions/8a44a4364f5a_initial_database_migration.py", line 25, in upgrade
    globals()["upgrade_%s" % engine_name]()
  File "/usr/lib/python3.9/site-packages/keylime/migrations/versions/8a44a4364f5a_initial_database_migration.py", line 34, in upgrade_registrar
    op.create_table('registrarmain',
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/lib/python3.9/site-packages/alembic/operations/ops.py", line 1252, in create_table
    return operations.invoke(op)
  File "/usr/lib/python3.9/site-packages/alembic/operations/base.py", line 374, in invoke
    return fn(self, operation)
  File "/usr/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/usr/lib/python3.9/site-packages/alembic/ddl/impl.py", line 258, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/lib/python3.9/site-packages/alembic/ddl/impl.py", line 140, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table registrarmain already exists
[SQL:
CREATE TABLE registrarmain (
        agent_id VARCHAR(80) NOT NULL,
        "key" VARCHAR(45),
        aik VARCHAR(500),
        ek VARCHAR(500),
        ekcert VARCHAR(2048),
        "virtual" INTEGER,
        active INTEGER,
        provider_keys TEXT,
        regcount INTEGER,
        PRIMARY KEY (agent_id)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by mpeters** [comment] 2021-01-25 17:30
@dnoliver since this db migration issue is a different issue, would you be able to open a new ticket to track it?

**Comment by lukehinds** [comment] 2021-01-25 17:33
I put this up to get discussions going : https://github.com/keylime/keylime/pull/523

this is a high priority, so let's try to avoid bike shedding over idioms and such, we can clean up / refine later.

**Comment by stefanberger** [comment] 2021-01-25 17:55
@dnoliver We ran into a DB upgrade problem and I submitted a fix for this: https://github.com/keylime/keylime/pull/515 . Does your build contain this fix?

**Comment by lukehinds** [comment] 2021-01-25 18:04
https://github.com/keylime/keylime/pull/524 for ima_file_signatures

@stefanberger I may need to cut a new release with #515 , I will check this.

**Comment by dnoliver** [comment] 2021-01-25 18:19
Will create a different issue and reproduction steps for the DB upgrade problem.

Now, related to `keylime_webapp` and the update in https://bodhi.fedoraproject.org/updates/FEDORA-2021-2c3a0c5c63, I have cleaned up my environment (reinstall everything and deleted /var/lib/keylime) and run into the following error while starting the webapp:

```shell
[root@fedora-server keylime]# keylime_webapp
Using config file /etc/keylime.conf
2021-01-25 15:11:36.752 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-01-25 15:11:36.753 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-01-25 15:11:36.753 - keylime.tenant_webapp - INFO - Starting Tenant WebApp (tornado) on port 443 use <Ctrl-C> to stop
2021-01-25 15:11:36.753 - keylime.tenant_webapp - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
Traceback (most recent call last):
  File "/usr/bin/keylime_webapp", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_webapp')())
  File "/usr/lib/python3.9/site-packages/keylime/cmd/webapp.py", line 15, in main
    tenant_webapp.main()
  File "/usr/lib/python3.9/site-packages/keylime/tenant_webapp.py", line 707, in main
    server_context = get_tls_context()
  File "/usr/lib/python3.9/site-packages/keylime/tenant_webapp.py", line 665, in get_tls_context
    context.load_cert_chain(
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by mpeters** [comment] 2021-01-25 18:54
You probably shouldn't delete `/var/lib/keylime` just everything in it. I'm guessing some parts of the keylime code assume it already exists because the installer should have created it.

**Comment by SeJohnEff** [comment] 2021-01-28 02:55
I confirmed today that keylime_webapp works OK on Ubuntu 18 LTS but I get same error on Ubuntu 20 and on vm (fedora 33).
"Exception: Static resource directory could not be found in /usr/lib/python3.9/site-packages/keylime!"

**Comment by dnoliver** [comment] 2021-01-28 15:59
> You probably shouldn't delete `/var/lib/keylime` just everything in it. I'm guessing some parts of the keylime code assume it already exists because the installer should have created it.

There are no missing files. The problem is that the paths are not calculated correctly. Added a couple of debug statement in the offending code and got the following:

```shell
[root@fedora-server keylime]# keylime_webapp
Using config file /etc/keylime.conf
2021-01-28 12:57:36.550 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-01-28 12:57:36.550 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-01-28 12:57:36.550 - keylime.tenant_webapp - INFO - Starting Tenant WebApp (tornado) on port 443 use <Ctrl-C> to stop
2021-01-28 12:57:36.551 - keylime.tenant_webapp - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2021-01-28 12:57:36.555 - keylime.tenant_webapp - INFO - my_tls_cert: /var/lib/keylime/cv_ca//var/lib/keylime/cv_ca/client-cert.crt
2021-01-28 12:57:36.555 - keylime.tenant_webapp - INFO - my_tls_priv_key: /var/lib/keylime/cv_ca//var/lib/keylime/cv_ca/client-private.pem
2021-01-28 12:57:36.555 - keylime.tenant_webapp - INFO - calling context.load_cert_chain(my_tls_cert, my_tls_priv_key)
Traceback (most recent call last):
  File "/usr/bin/keylime_webapp", line 33, in <module>
    sys.exit(load_entry_point('keylime==0.0.0', 'console_scripts', 'keylime_webapp')())
  File "/usr/lib/python3.9/site-packages/keylime/cmd/webapp.py", line 15, in main
    tenant_webapp.main()
  File "/usr/lib/python3.9/site-packages/keylime/tenant_webapp.py", line 710, in main
    server_context = get_tls_context()
  File "/usr/lib/python3.9/site-packages/keylime/tenant_webapp.py", line 668, in get_tls_context
    context.load_cert_chain(
FileNotFoundError: [Errno 2] No such file or directory
```

It is appending the basedir to an already global path.

**Comment by dnoliver** [comment] 2021-02-12 17:14
any new updates to test? 

I manually changed my `tenant_webapp.py` to workaround the problem described above:

```diff
[root@fedora-server test]# diff ./keylime/keylime/tenant_webapp.py /usr/lib/python3.9/site-packages/keylime/tenant_webapp.py
660,661c660,665
<     my_tls_cert = "%s/%s" % (tls_dir, my_cert)
<     my_tls_priv_key = "%s/%s" % (tls_dir, my_priv_key)
---
>     my_tls_cert = "%s" % (my_cert)
>     my_tls_priv_key = "%s" % (my_priv_key)
>
>     logger.info("ca_path: %s", ca_path)
>     logger.info("my_tls_cert: %s", my_tls_cert)
>     logger.info("my_tls_priv_key: %s", my_tls_priv_key)
664a669
>     logger.info("calling context.load_cert_chain(my_tls_cert, my_tls_priv_key)")
```

**Comment by MartinMa28** [comment] 2021-02-26 09:40
> You probably shouldn't delete `/var/lib/keylime` just everything in it. I'm guessing some parts of the keylime code assume it already exists because the installer should have created it.

Has nothing to do with '/var/lib/keylime'. keylime_webapp has the same problem in ansible tpm emulator. 
It works after: 
1. copy static files from /static to the installed python site-packages directory 
2. make the code change in tenant_webapp.py like @dnoliver mentioned

**Comment by lukehinds** [comment] 2021-03-09 10:43
I will push this out to fedora this week

apologies for the breakages, not many use the GUI. its actually more of a prototype, maybe this merits us improving the whole UI code base.

**Comment by mpeters** [comment] 2022-03-02 14:09
@THS-on do you know if this is changed by the changes we made for python packaging?

**Comment by THS-on** [comment] 2022-03-06 10:40
@mpeters it is still broken. Should be a simple fix. Can you assign me to this issue?

**Closed** 2022-03-14 14:17 UTC
