### ISSUE TITLE
invoke_get_quote fails on tornado 6.0 

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#196] opened 2019-10-17 12:19 UTC
The 'callback` function has been deprecated in 6.0 release:

https://www.tornadoweb.org/en/stable/releases/v6.0.0.html

This results in the following code breaking:

https://github.com/keylime/keylime/blob/7c6e0ea539d3952991e77eaefb57fbf14b83ea4e/keylime/cloud_verifier_tornado.py#L295-L307

and possibly...

https://github.com/keylime/keylime/blob/7c6e0ea539d3952991e77eaefb57fbf14b83ea4e/keylime/revocation_notifier.py#L71-L90

```
Using config file /etc/keylime.conf
2019-10-17 12:09:44.918 - keylime.cloudverifier - INFO - Starting Cloud Verifier (tornado) on port 8881, use <Ctrl-C> to stop
2019-10-17 12:09:44.919 - keylime.cloudverifier_common - INFO - Setting up TLS...
2019-10-17 12:09:44.920 - keylime.cloudverifier_common - INFO - Existing CA certificate found in /var/lib/keylime/cv_ca, not generating a new one
2019-10-17 12:09:44.922 - keylime.cloudverifier - INFO - Starting service for revocation notifications on port 8992
2019-10-17 12:10:33.188 - keylime.cloudverifier - ERROR - Polling thread error: __init__() got an unexpected keyword argument 'callback'
2019-10-17 12:10:33.189 - keylime.cloudverifier - ERROR - __init__() got an unexpected keyword argument 'callback'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/cloud_verifier_tornado.py", line 406, in process_agent
    self.invoke_get_quote(agent, True)
  File "/usr/local/lib/python3.7/site-packages/keylime-1.2-py3.7.egg/keylime/cloud_verifier_tornado.py", line 307, in invoke_get_quote
    client.fetch(url, callback=cb)
  File "/usr/local/lib64/python3.7/site-packages/tornado/httpclient.py", line 284, in fetch
    request = HTTPRequest(url=request, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'callback'
2019-10-17 12:10:33.192 - keylime.cloudverifier - INFO - POST returning 200 response for adding agent id: D432FBB3-D2F1-4A97-9EF7-75BD81C00000
2019-10-17 12:10:33.486 - keylime.cloudverifier - INFO - PUT returning 404 response. agent id: D432FBB3-D2F1-4A97-9EF7-75BD81C00000 not found.
```

I guess we will need to replace this with async code.

**Comment by jetwhiz** [comment] 2019-10-17 15:49
Can we just use `add_done_callback` to keep the same functionality, even though it's intended to be low-level? 

So something like: 
````python
     url = "http://%s:%d/quotes/integrity?nonce=%s&mask=%s&vmask=%s&partial=%s"%(agent['ip'],agent['port'],params["nonce"],params["mask"],params['vmask'],partial_req) 
     # the following line adds the agent and params arguments to the callback as a convenience 
     cb = functools.partial(self.on_get_quote_response, agent, url) 
     client.fetch(url).add_done_callback(cb)
````

**Comment by lukehinds** [comment] 2019-10-17 16:25
If its a simple as that, this would be great. I will test it first thing in the morning.

**Comment by lukehinds** [comment] 2019-10-22 11:48
Hmm, I am not getting anywhere with this one.

I think we might need to use Futures

I tried out the code you suggested

On the verifier:

```
2019-10-22 11:23:14.634 - keylime.cloudverifier - INFO - PUT returning 404 response. agent id: D432FBB3-D2F1-4A97-9EF7-75BD81C00000 not found.
```

tenant:

```
Using config file /etc/keylime.conf
2019-10-22 11:23:14.133 - keylime.tenant - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2019-10-22 11:23:14.134 - keylime.tenant - INFO - Setting up client TLS in /var/lib/keylime/cv_ca
2019-10-22 11:23:14.139 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x408000
2019-10-22 11:23:14.139 - keylime.tenant - INFO - TPM PCR Mask from policy is 0x808000
2019-10-22 11:23:14.139 - keylime.ima - WARNING - No boot_aggregate value found in whitelist, adding an empty one
2019-10-22 11:23:14.566 - keylime.registrar_client - INFO - Setting up client TLS...
2019-10-22 11:23:14.587 - keylime.registrar_client - WARNING - CAUTION: using default password for private key, please set private_key_pw to a strong password
2019-10-22 11:23:14.614 - keylime.tpm2 - INFO - TPM2-TOOLS Version: 4.0
2019-10-22 11:23:14.634 - keylime.tenant - ERROR - Response code 404: agent id not found
Traceback (most recent call last):
  File "/usr/local/bin/keylime_tenant", line 11, in <module>
    load_entry_point('keylime==1.2', 'console_scripts', 'keylime_tenant')()
  File "/usr/local/lib/python3.8/site-packages/keylime-1.2-py3.8.egg/keylime/tenant.py", line 805, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.8/site-packages/keylime-1.2-py3.8.egg/keylime/tenant.py", line 699, in do_quote
    raise e
  File "/usr/local/lib/python3.8/site-packages/keylime-1.2-py3.8.egg/keylime/tenant.py", line 661, in do_quote
    if not self.validate_tpm_quote(public_key, quote, tpm_version, hash_alg):
  File "/usr/local/lib/python3.8/site-packages/keylime-1.2-py3.8.egg/keylime/tenant.py", line 396, in validate_tpm_quote
    if not tpm.check_quote(self.nonce,public_key,quote,reg_keys['aik'],hash_alg=hash_alg):
  File "/usr/local/lib/python3.8/site-packages/keylime-1.2-py3.8.egg/keylime/tpm2.py", line 1075, in check_quote
    jsonout = common.yaml_to_dict(retout)
  File "/usr/local/lib/python3.8/site-packages/keylime-1.2-py3.8.egg/keylime/common.py", line 265, in yaml_to_dict
    return yaml.load("\n".join(arry),  Loader=SafeLoader)
  File "/usr/lib64/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib64/python3.8/site-packages/yaml/constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 7, column 1
could not find expected ':'
  in "<unicode string>", line 8, column 1
```

This is `retout` send to `  jsonout = common.yaml_to_dict(retout)` in `tpm2.py`

```
retout: [b'pcrs:\n', b'  sha256:\n', b'    0 : 0x0000000000000000000000000000000000000000000000000000000000000000\n', b'32b364c4945fd2a94217f77dc18e533b3925f4c31312c24c8557a8a0ac847c629d9f6893dce16c5ca36236f4af0822c132f69a0ec17933c645b95cf22e399d2ae6d8a186f4c8e5bcb5f71332065b75bd8b819b11226bee7f39d52d303db434d54cf59b1480b646f8ae4b3881e1f2cf3a79f3be03e035aa450df5707d500b399104d08624b210850fb3f9b9503e2b13d10e716ef095ef1490dbe14e8fc27cb013e2a18c2f931d00b26b8a5cf7816ab7d2fa76f8c798d920bbc2e084a12cc8c09463cdef39dba8b973efe7dec54e468c27ec54c98c50c76a0fac93774ce557c04ed959898940e94b63e32004bdf84f91200752ffe00256e088b4b605fdbba274f2']
```

How is your availability to take this one on @jetwhiz ?

**Comment by jetwhiz** [comment] 2019-10-24 13:12
Hi @lukehinds 

Sorry for the delay, I've been swamped this week.  This error doesn't look related to tornado, and is likely caused by the (now fixed) upstream tpm2-tools issue here: https://github.com/tpm2-software/tpm2-tools/issues/1782

This will be released when 4.0.1 comes out, but is still broken in what Fedora has in its repos.  If we want this to work right now then we'll have to build from source on [4.0.X](https://github.com/tpm2-software/tpm2-tools/tree/4.0.X) or `master`.

**Comment by lukehinds** [comment] 2019-10-24 13:13
> Hi @lukehinds
> 
> Sorry for the delay, I've been swamped this week. This error doesn't look related to tornado, and is likely caused by the (now fixed) upstream tpm2-tools issue here: [tpm2-software/tpm2-tools#1782](https://github.com/tpm2-software/tpm2-tools/issues/1782)
> 
> This will be released when 4.0.1 comes out, but is still broken in what Fedora has in its repos. If we want this to work right now then we'll have to build from source on [4.0.X](https://github.com/tpm2-software/tpm2-tools/tree/4.0.X) or `master`.

Understood, thanks for looking into this charlie!

**Comment by lukehinds** [comment] 2019-10-31 20:45
@jetwhiz 

just coming back to this issue. unfortunately using `add_done_callback(cb)` does not return back like the original callback param, so you just get a single quote happen and then the code stops running - no exception, just as it does not return it gets stuck in self.on_get_quote_response

It seems you have to couple if with `Futures()` 

I have been trying something like this:

```
future = client.fetch(url)
future.add_done_callback(functools.partial(self.on_get_quote_response, agent, url))
```

And many other variations.

What I can't work out, is how `response` is being passed to the function its created in

`def on_get_quote_response(self, agent, url, response):`

I guess this was something unique to callback

If you fancy a go at this, please do @jetwhiz - I have tried rewriting with a while True loop, but I cannot capture the agent being deleted.

**Comment by lukehinds** [comment] 2019-10-31 21:37
I admit defeat here!

Been at this for six hours and I can't dicpher how this is mean to work;

```
cb = functools.partial(self.on_get_quote_response, agent, url)
client.fetch(url, callback=cb)
```

I can't see why we would send the`url` to `on_get_quote_response`, when we fetch the `url` with `client.fetch`.

This may be my shortcoming in understanding here, but I can't grok what we are doing.

**Comment by jetwhiz** [comment] 2019-11-01 19:51
Hi @lukehinds 

I haven't found a way to do this without the using [nest-asyncio](https://pypi.org/project/nest-asyncio/) PIP package. It sounds like python and tornado developers are trying to [prevent developers from doing recursive event loops](https://bugs.python.org/issue22239), which we need here.  

If you're willing to use (and install) the `nest-asyncio` pip package, then here is a patch to `cloud_verifier_tornado.py` that works on my end. 

````diff
diff --git a/keylime/cloud_verifier_tornado.py b/keylime/cloud_verifier_tornado.py
index f884952..31b9ca6 100644
--- a/keylime/cloud_verifier_tornado.py
+++ b/keylime/cloud_verifier_tornado.py
@@ -24,6 +24,8 @@ import traceback
 import sys
 import functools
 import asyncio
+import nest_asyncio
+nest_asyncio.apply()
 
 import tornado.ioloop
 import tornado.web
@@ -293,6 +295,9 @@ class AgentsHandler(BaseHandler):
 
 
     def invoke_get_quote(self, agent, need_pubkey):
+        asyncio.get_event_loop().run_until_complete(self._invoke_get_quote(agent, need_pubkey))
+
+    async def _invoke_get_quote(self, agent, need_pubkey):
         params = cloud_verifier_common.prepare_get_quote(agent)
         agent['operational_state'] = cloud_verifier_common.CloudAgent_Operational_State.GET_QUOTE
         client = tornado.httpclient.AsyncHTTPClient()
@@ -302,11 +307,8 @@ class AgentsHandler(BaseHandler):
             partial_req = "0"
 
         url = "http://%s:%d/quotes/integrity?nonce=%s&mask=%s&vmask=%s&partial=%s"%(agent['ip'],agent['port'],params["nonce"],params["mask"],params['vmask'],partial_req)
-        # the following line adds the agent and params arguments to the callback as a convenience
-        cb = functools.partial(self.on_get_quote_response, agent, url)
-        client.fetch(url, callback=cb)
-
-    def on_get_quote_response(self, agent, url, response):
+        response = await client.fetch(url)
+        
         if agent is None:
             raise Exception("agent deleted while being processed")
         if response.error:
@@ -341,17 +343,19 @@ class AgentsHandler(BaseHandler):
 
 
 
+
     def invoke_provide_v(self, agent):
+        asyncio.get_event_loop().run_until_complete(self._invoke_provide_v(agent))
+
+    async def _invoke_provide_v(self, agent):
         if agent['pending_event'] is not None:
             agent['pending_event'] = None
         v_json_message = cloud_verifier_common.prepare_v(agent)
         agent['operational_state'] = cloud_verifier_common.CloudAgent_Operational_State.PROVIDE_V
         client = tornado.httpclient.AsyncHTTPClient()
         url = "http://%s:%d/keys/vkey"%(agent['ip'],agent['port'])
-        cb = functools.partial(self.on_provide_v_response, agent, url)
-        client.fetch(url, method="POST", callback=cb, headers=None, body=v_json_message)
+        response = await client.fetch(url, method="POST", headers=None, body=v_json_message)
 
-    def on_provide_v_response(self, agent, url_with_params, response):
         if agent is None:
             raise Exception("Agent deleted while being processed")
         if response.error:
````

What do you think?

**Comment by lukehinds** [comment] 2019-11-01 20:12
Thanks @jetwhiz , appreciate you looking into it. 

I was trying to build a while true loop by combining `invoke_get_quote` with `on_get_quote_response`, but not getting anywhere.

The  `nest-asyncio` looks good, but it seems its not packaged in Fedora. Fedora won't allow pip installs in the build systems, it would need a `python3-nest-asyncio` package. I figure it might be be supported as it directly patches python code. 

:(

**Comment by lukehinds** [comment] 2019-11-01 20:15
Is a coroutine a possibility?

**Comment by jetwhiz** [comment] 2019-11-01 20:31
It might be able to be done with coroutines, but I was concerned that a lot of methods might have to be converted into an `awaitable` if we do that with `async`.  Do you know of a clean way to only have a limited number methods affected?

**Comment by lukehinds** [comment] 2019-11-01 20:34
Yes, the dreaded async creep. 

Last time I tried, it got so messy I brought in `http.client` as async kept working its way all the way back to `main()`

Am I right in thinking this, we don't need non blocking calls into the agent, as the agent has no need to be non blocking - thats a need of just the verifier?

**Comment by jetwhiz** [comment] 2019-11-01 21:11
I'm not aware of anything non-blocking in the agent -- this is mostly used for the verifier so it can handle a large number of requests from various agents.

**Closed** 2019-11-17 18:40 UTC
Labels: bug, key_feature
