### ISSUE TITLE
keylime_tenant seems to read verifier.conf

### ISSUE THREAD

**Issue by kkaarreell** [keylime/keylime#1541] opened 2024-04-05 14:17 UTC
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: Fedora 40
 * Processor architecture: x86_64
 * TPM Manufacturer: swtpm
 * Keylime version: current upstream [ea0cc9f](https://github.com/keylime/keylime/commit/ea0cc9f9522c1a0c753e10272fba90df75dd3a42)

# Description 
in keylime_tenant outout one can see that verifier.conf is read.
For example:
```
$ keylime_tenant -v 127.0.0.1 -t 127.0.0.1 -u d432fbb3-d2f1-4a97-9ef7-75bd81c00000 --verify --runtime-policy policy.json --cert default -c add

INFO:keylime.config:Reading configuration from ['/etc/keylime/logging.conf']
2024-03-20 13:05:58.186 - keylime.config - INFO - Reading configuration from ['/etc/keylime/tenant.conf']
2024-03-20 13:05:58.187 - keylime.tenant - INFO - Setting up client TLS...
2024-03-20 13:05:58.187 - keylime.tenant - INFO - Using default client_cert option for tenant
2024-03-20 13:05:58.187 - keylime.tenant - INFO - Using default client_key option for tenant
2024-03-20 13:05:58.187 - keylime.tenant - INFO - No value provided in client_key_password option for tenant, assuming the key is unencrypted
2024-03-20 13:05:58.194 - keylime.tenant - INFO - TLS is enabled.
2024-03-20 13:05:58.194 - keylime.config - INFO - Reading configuration from ['/etc/keylime/verifier.conf']
2024-03-20 13:05:58.240 - keylime.cli.policies - INFO - TPM PCR Mask from policy is 0x0
2024-03-20 13:05:58.240 - keylime.config - INFO - Reading configuration from ['/etc/keylime/ca.conf']
2024-03-20 13:05:58.240 - keylime.ca-util - WARNING - The 'default' password option from CA configuration file cannot be used with keylime CLI (keylime_tenant or keylime_ca)
...
```
Previously, I have reported similar issue https://github.com/keylime/keylime/issues/1446, I don't know if this is related though.

## Expected behavior vs. actual behavior 
keylime_tenant should not access verifier.conf, probably even ca.conf

## Steps to reproduce problem
1.  run keylime_tenant command

**Comment by kkaarreell** [comment] 2024-05-02 10:40
When there is no `verifier.conf` on the system I can see tenant to fail
```
2024-05-02 06:31:58.711 - keylime.config - WARNING - Config file not found in ['/etc/keylime/verifier.conf', '/usr/etc/keylime/verifier.conf']. It is required by component /usr/lib/python3.12/site-packages/keylime/config.py. 
Please use "keylime_upgrade_config --defaults" to create a minimalistic set of configurations.

2024-05-02 06:31:58.711 - keylime.tenant - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/keylime/mba/mba.py", line 69, in load_imports
    imports = config.getlist("verifier", "measured_boot_imports")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/keylime/config.py", line 260, in getlist
    read = get_config(component).get(section, option).strip('" ')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/configparser.py", line 1130, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'verifier'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/keylime/cmd/tenant.py", line 10, in main
    tenant.main()
  File "/usr/lib/python3.12/site-packages/keylime/tenant.py", line 1598, in main
    mytenant = Tenant()
               ^^^^^^^^
  File "/usr/lib/python3.12/site-packages/keylime/tenant.py", line 160, in __init__
    mba.load_imports()
  File "/usr/lib/python3.12/site-packages/keylime/mba/mba.py", line 78, in load_imports
    raise ValueError from e
ValueError
```

**Comment by stefanberger** [comment] 2024-05-02 17:45
Does the tenant need mba at all?
```
# grep mba keylime/tenant.py
from keylime.mba import mba
        mba.load_imports()
```

This was added in c99103b3f5:

```
diff --git a/keylime/tenant.py b/keylime/tenant.py
index 9070817..3b93d05 100644
--- a/keylime/tenant.py
+++ b/keylime/tenant.py
@@ -21,6 +21,7 @@ from keylime.cli import options, policies
 from keylime.cmd import user_data_encrypt
 from keylime.common import algorithms, retry, states, validators
 from keylime.ip_util import bracketize_ipv6
+from keylime.mba import mba
 from keylime.requests_client import RequestsClient
 from keylime.tpm import tpm2_objects, tpm_util
 from keylime.tpm.tpm_main import Tpm
@@ -156,6 +157,8 @@ class Tenant:
         else:
             logger.warning("TLS is disabled.")

+        mba.load_imports()
+
     @property
     def verifier_base_url(self) -> str:
         return f"{bracketize_ipv6(self.verifier_ip)}:{self.verifier_port}"
```

**Comment by THS-on** [comment] 2024-06-19 14:42
@stefanberger I saw that the PR got closed without being merged, what was the reason for that and is this issue still there?

**Comment by stefanberger** [comment] 2024-06-19 14:48
> @stefanberger I saw that the PR got closed without being merged, what was the reason for that and is this issue still there?

The changes in that PR didn't work.

**Comment by stefanberger** [comment] 2024-06-19 15:11
> > @stefanberger I saw that the PR got closed without being merged, what was the reason for that and is this issue still there?
> 
> The changes in that PR didn't work.

In particular one ends up running into this kind of issue then:
```
> keylime_tenant -c update --uuid $agentuuid -f payload --runtime-policy ./mypolicy.json
[...]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keylime/mba/mba.py", line 102, in bootlog_parse
    m = _find_implementation("bootlog_parse")
  File "/usr/local/lib/python3.9/site-packages/keylime/mba/mba.py", line 187, in _find_implementation
    raise ValueError(f"No implementation for function {functionname} found among measured boot imports")
ValueError: No implementation for function bootlog_parse found among measured boot imports


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keylime/cmd/tenant.py", line 10, in main
    tenant.main()
  File "/usr/local/lib/python3.9/site-packages/keylime/tenant.py", line 1701, in main
    mytenant.do_quote()
  File "/usr/local/lib/python3.9/site-packages/keylime/tenant.py", line 1139, in do_quote
    if not self.validate_tpm_quote(public_key, quote, algorithms.Hash(hash_alg)):
  File "/usr/local/lib/python3.9/site-packages/keylime/tenant.py", line 501, in validate_tpm_quote
    failure = self.tpm_instance.check_quote(
  File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 478, in check_quote
    return self.check_pcrs(
  File "/usr/local/lib/python3.9/site-packages/keylime/tpm/tpm_main.py", line 241, in check_pcrs
    mb_pcrs_hashes, boot_aggregates, mb_measurement_data, mb_failure = mba.bootlog_parse(
  File "/usr/local/lib/python3.9/site-packages/keylime/mba/mba.py", line 105, in bootlog_parse
    raise ValueError from e
ValueError
```

**Comment by marcostork** [comment] 2024-07-10 14:33
Does the tenant need to check the pcr while checking the quote? If not, I believe it is possible to remove the mba from the tenant and just set skip_pcr_check = True. Otherwise, check_pcrs has to be reviewed because it always tries to parse the binary boot log (maybe it should be reviewed anyway).

**Comment by marcostork** [comment] 2024-07-10 18:44
@stefanberger, does the tenant need to check the pcr while checking the quote? If it doesn't, it is possible to remove the mba from the tenant and just set skip_pcr_check = True. Otherwise, check_pcrs has to be reviewed because it always tries to parse the binary boot log (maybe it should be reviewed anyway).

**Comment by stefanberger** [comment] 2024-07-10 19:27
I had the impression that the tentant tool needs the list of plugins from the verifier.conf. But it's been a while that I looked at it.

**Comment by kkaarreell** [comment] 2024-07-15 11:13
I do not know details but definitely verifier.conf was not required in the past. In keylime-tests we are running a multihost test which configures just the respective config file on each guest and the test was passing in the past (it is passing with keylime version from RHEL-9). Nowadays, it is failing with the previously mentioned error
```
2024-07-15 02:45:31.332 - keylime.tenant - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/keylime/mba/mba.py", line 69, in load_imports
    imports = config.getlist("verifier", "measured_boot_imports")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/keylime/config.py", line 260, in getlist
    read = get_config(component).get(section, option).strip('" ')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'verifier'
```

**Comment by ansasaki** [comment] 2024-08-06 08:27
@stefanberger @marcostork Any updates on this?

**Comment by marcostork** [comment] 2024-08-06 17:21
@ansasaki 
The issue is caused by the MBA module loaded on the tenant. Whenever the tenant needs to add or update a policy, it uses validate_tpm_quote() to check the quote received from the agent. This function, part of the TPM module, verifies the signature, nonce, and other elements and then proceeds to check the PCRs, which is where the MBA module comes into play.

The MBA module requires the list of modules (and the modules themselves, if any) to verify the PCRs. The verifier maintains this information.

If policy checking is indeed the tenant's responsibility, this information must be made available through other means. Now, suppose you delegate this responsibility only to the verifier. In that case, the tenant won't need the MBA module and there are two ways to proceed: either skip the PCR check (the check_quote function in the TPM module anticipates this) or modify check_pcrs in the TPM module to validate the PCR data only and skip the policies check.

**Comment by marcostork** [comment] 2024-08-06 18:00
In that case, it is an easy fix. We remove mba from the tenant (import and load_imports) and set skip_pcr_check to True in check_quote (in tenant.py). It would still validate the quote but not the pcrs (and policies). Should I open a PR?

**Comment by maugustosilva** [comment] 2024-08-06 21:00
> In my opinion, the tenant should not be responsible for verifying quotes in any way. It can validate the format of the input data, but verifying policies should be only done by the verifier.

@ansasaki this is a pretty big change, and should be discussed on the next monthly meeting. On the original `keylime` mode of operation, multiple `tenants` (party A) could share a single `verifier`/`registrar` infrastructure (party B), and the lack of trust between these two parties required the `agent` to prove himself (via quote+nonce) to both. I believe there is an argument to be made that the `tenant` does not need to validate the policies, an (IMO, weaker) argument that it should not validate the PCRs, but the quote+nonce is, I believe, essential to the current threat/security model.

**Comment by maugustosilva** [comment] 2024-08-06 21:01
> In that case, it is an easy fix. We remove mba from the tenant (import and load_imports) and set skip_pcr_check to True in check_quote (in tenant.py). It would still validate the quote but not the pcrs (and policies). Should I open a PR?

@marcostork please go ahead and open the PR. It will be a good launching pad for the discussion. It looks like (again, IMO), a pretty decent compromise.

**Comment by marcostork** [comment] 2024-08-06 21:18
@maugustosilva Considering that requirement, I will proceed with the PCR check implementation and effectively skip only the policy check.

**Comment by THS-on** [comment] 2024-08-07 11:23
Adding to https://github.com/keylime/keylime/issues/1541#issuecomment-2272143425, there is also the need to bind the agent to its transport key which is done using the resettable PCR. This key is currently required for the payload mechanism. We can probably eliminate the transport key, as discussed before, but skipping the PCR validation would break the payload mechanism right now.

**Comment by ansasaki** [comment] 2024-08-07 12:14
I think it should be possible to fix the regression that the tenant now requires the `verifier.conf` without any deep changes since it was working before.

> > In my opinion, the tenant should not be responsible for verifying quotes in any way. It can validate the format of the input data, but verifying policies should be only done by the verifier.
> 
> @ansasaki this is a pretty big change, and should be discussed on the next monthly meeting. On the original `keylime` mode of operation, multiple `tenants` (party A) could share a single `verifier`/`registrar` infrastructure (party B), and the lack of trust between these two parties required the `agent` to prove himself (via quote+nonce) to both. I believe there is an argument to be made that the `tenant` does not need to validate the policies, an (IMO, weaker) argument that it should not validate the PCRs, but the quote+nonce is, I believe, essential to the current threat/security model.

The registrar and verifier require the tenant certificate, and vice-versa. I don't understand how they can be untrusted to each other.

The nonce is generated and verified by the registrar with `TPM2_MakeCredential/TPM2_ActivateCredential`. It has nothing to do with the tenant AFAIK.

I think that it is OK if the tenant wants to check a quote. The problem is requiring `verifier.conf` for that.

> Adding to [#1541 (comment)](https://github.com/keylime/keylime/issues/1541#issuecomment-2272143425), there is also the need to bind the agent to its transport key which is done using the resettable PCR. This key is currently required for the payload mechanism. We can probably eliminate the transport key, as discussed before, but skipping the PCR validation would break the payload mechanism right now.

The usage of the debug PCR#16 for this purpose is extremely ugly in my opinion and we should aim to remove this from Keylime. There are other mechanisms for that, probably using `TPM2_Certify` or `TPM2_MakeCredential/TPM2_ActivateCredential`.

**Comment by maugustosilva** [comment] 2024-08-07 14:03
@ansasaki one of the main purposes of "durable attestation" was to make the `verifier` untrusted. Anyway, as it stands today, the use of PCR#16, as ugly as it is, it is required for the payload mechanism (which is heavily used by some customs, even in production).

**Closed** 2024-08-12 18:40 UTC
