### ISSUE TITLE
keylime/keylime' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by blackdobb** [keylime/keylime#1102] opened 2022-09-15 12:21 UTC
Is your an issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version:  Ubuntu 20.04
 * Processor architecture: 
 * TPM Manufacturer: 
 * Keylime version: 

# Description 
I'm new here, I want to install keylime and test it if it works properly. But I stuck at the first step. When I was installing it with "sudo ./installer.sh -k", there always an error happend:

`
fatal: destination path '/home/test/coding/keylime/keylime' already exists and is not an empty directory.
/home/test/coding/keylime/keylime /home/test/coding/keylime
Already on 'master'
Your branch is up to date with 'origin/master'.
/home/test/coding/keylime
ERROR: Invalid keylime directory at /home/test/coding/keylime/keylime
`
How could I install and use it properly? I have no idea about solving this problem.
## Steps to reproduce problem
1. 

# Relevant logs

Attach any relevant log files that can help to debug your issue.

**Comment by mpeters** [comment] 2022-09-15 13:02
You shouldn't need the `-k` option if you are running the installer from a git checkout. The `-k` is for using the installer script standalone on someplace without the code already present.

**Comment by blackdobb** [comment] 2022-09-16 01:49
> 

Thanks for your reply. But I still have no idea of deploying the Keylime. I have two ubuntu 20.04 machines, and want to achive the case in https://keylime.dev/. The Biggest problem is what operations should be done on each machine? how to Start the verifier?

Now I started keylime-fedora1 on the one of the machine, and it waiting for domain to get an IP address, what should I do on the other machine?

I would be grateful if you could help me on this matter.

**Comment by blackdobb** [comment] 2022-09-16 01:49
> `-k`如果您从 git checkout 运行安装程序，则不需要该选项。`-k`用于在没有代码的情况下在某个地方独立使用安装程序脚本。

Thanks for your reply. But I still have no idea of deploying the Keylime. I have two ubuntu 20.04 machines, and want to achive the case in https://keylime.dev/. The Biggest problem is what operations should be done on each machine? how to Start the verifier?

Now I started keylime-fedora1 on the one of the machine, and it waiting for domain to get an IP address, what should I do on the other machine?

I would be grateful if you could help me on this matter.

**Comment by THS-on** [comment] 2022-10-24 19:35
@blackdobb did you get it working?

Because this is not a bug and more of a setup question, I'll close this. If you have any issues setting up Keylime the best place to ask is on the `#keylime` channel on the CNCF Slack.

**Closed by THS-on** 2022-10-24 19:35 UTC
